import React, { useEffect, useState } from 'react'
import useData from './custumHools/useData'

function FakeApi() {
    // const [data, setData] = useState([])
    const [data]=useData('https://dummyjson.com/products//category/smartphones')


    if (Math.random() > 0.5) {
        return new Error("Test Error Boundary")
      }
    // console.log(data)

    return (

        <div>
            {data && data.map((item,index) => {
                return <h1 key={index
                }>
                    {item.title}
                </h1>
            })}

<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1><h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>
<h1>this is homw</h1>

        </div>
    )
}

export default FakeApi